apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: edusphere-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: edusphere
  endpoints:
  - port: http
    interval: 15s
    